const assert = require('node:assert/strict');
const fs = require('node:fs');
const crypto = require('node:crypto');
const ui = require('../assets/revenue-observation.js');
const html=fs.readFileSync('index.html','utf8');
const bytes=fs.readFileSync('assets/revenue-observation.js','utf8').replace(/\r\n/g,'\n');
const hash=crypto.createHash('sha256').update(bytes).digest('hex').slice(0,12);
assert(html.includes(`assets/revenue-observation.js?v=${hash}`));
assert(html.includes('revenueObservationRows'));
assert(ui.table({rows:[]}).includes('尚無符合'));
const row={symbol:'2330',name:'<img onerror="bad">',subject:'<script>bad</script>',evidence:'成長',rev_yoy:10,rev_mom:5,status:'waiting'};
const waiting=ui.table({rows:[row]});
assert(!waiting.includes('<script>') && !waiting.includes('<img'));
assert(waiting.includes('等待收盤'));
assert(waiting.includes('<td>—</td></tr>'));
const done=ui.table({rows:[{...row,status:'complete',outcome:{open:100,high:105,low:98,close:102,open_pct:0,high_pct:5,low_pct:-2,close_pct:2,open_to_close_pct:2}}]});
assert(done.includes('+2.00%') && done.includes('-2.00%'));
assert(ui.summary({summary:{total:1,complete:0,up_rate:null,mean_close_pct:null}}).includes('—'));
console.log('PASS next-session observation UI, missing values, escaping and asset digest');
